### ISSUE TITLE
Исследование: количество запросов

### ISSUE THREAD

**Issue by rosshkaa** [moevm/mse_voice_acting_of_activity_on_the_github#3]
Гитхаб представляет только следующую информацию: время пуша, сколько коммитов, название репозитория и хеш суммы всех коммитов.
Можно с помощью запросов посмотреть дополнительную информацию(текст issue, комментарии и т.д.), но будет превышен лимит запросов в 5к/час.
 
Необходимо изучить, какое количество информации можно получить, основываясь на указанном лимите запросов, с учетом, что обновление данных происходит 6 раз в минуту.

**Comment by aaaaaa2493** [comment]
Строго говоря, каждый event выглядит вот так

```
{'actor': {'avatar_url': 'https://avatars.githubusercontent.com/u/8024973?',
           'display_login': 'csieber',
           'gravatar_id': '',
           'id': 8024973,
           'login': 'csieber',
           'url': 'https://api.github.com/users/csieber'},
 'created_at': '2018-09-28T08:51:28Z',
 'id': '8336745308',
 'payload': {'before': '5862c776a0b0a4ab6c5c46ed7ccec1d2b632334a',
             'commits': [{'author': {'email': 'c.sieber@tum.de',
                                     'name': 'Christian Sieber'},
                          'distinct': True,
                          'message': 'Update README.md',
                          'sha': 'ab6f1987f1aebd1aaa7fd0f06be7af0cde9e2e33',
                          'url': 'https://api.github.com/repos/s-schwarzmann/docker-video-encoding/commits/ab6f1987f1aebd1aaa7fd0f06be7af0cde9e2e33'}],
             'distinct_size': 1,
             'head': 'ab6f1987f1aebd1aaa7fd0f06be7af0cde9e2e33',
             'push_id': 2914943950,
             'ref': 'refs/heads/master',
             'size': 1},
 'public': True,
 'repo': {'id': 111729721,
          'name': 's-schwarzmann/docker-video-encoding',
          'url': 'https://api.github.com/repos/s-schwarzmann/docker-video-encoding'},
 'type': 'PushEvent'}
```


Из этой инфы также можно создать ссылку на изменения, вот её шаблон
https://github.com/{repo_name}/commit/{commit_hash}

А вот пример на основе события выше
https://github.com/s-schwarzmann/docker-video-encoding/commit/ab6f1987f1aebd1aaa7fd0f06be7af0cde9e2e33

**Comment by aaaaaa2493** [comment]
Количество всех событий и количество push - событий (может зависеть от времени, например ночью меньше, днём больше или наоборот т.к. в америке могут коммитить больше или меньше чем в европе с азией)

09:05:48-09:06:00, events: 291, pushes: 159 
09:06:00-09:06:11, events: 266, pushes: 140 
09:06:11-09:06:22, events: 284, pushes: 157 
09:06:23-09:06:34, events: 244, pushes: 130 
09:06:34-09:06:45, events: 242, pushes: 118 
09:06:45-09:06:55, events: 237, pushes: 121 
09:06:56-09:07:07, events: 222, pushes: 110 
09:07:08-09:07:18, events: 293, pushes: 144 
09:07:18-09:07:32, events: 276, pushes: 150 
09:07:30-09:07:41, events: 274, pushes: 153 
09:07:41-09:07:52, events: 240, pushes: 102 
09:07:52-09:08:03, events: 280, pushes: 114 
09:08:03-09:08:14, events: 265, pushes: 122 
09:08:15-09:08:25, events: 293, pushes: 143 
09:08:26-09:08:37, events: 246, pushes: 123 
09:08:37-09:08:48, events: 261, pushes: 117 
09:08:48-09:08:59, events: 240, pushes: 125
