### ISSUE TITLE
Макет интерфейса

### ISSUE THREAD

**Issue by rosshkaa** [moevm/mse_voice_acting_of_activity_on_the_github#4]
Необходимо разработать базовый макет интерфейса по аналогии с http://listen.hatnote.com/ содержащий следующие элементы интерфейса:
- Макет поля для отрисовки активности
- Список последней активности
- Частоту ивентов
- Описание проекта

**Comment by ierikhon** [comment]
Предлагаю обсудить непосредственно внешний вид и организацию интерфейса, прежде чем разрабатывать. 
На данный момент это максимально простой концепт(цвета, шрифты и прочие элементы декора естественно можно изменить). Отрисовка планируется на элементе canvas(с возможной заменой на svg при необходимости). Внизу - частота ивентов, описание проекта на отдельной html-странице. Список активности можно сделать в виде выдвижной панели снизу.

![giszbwhz5bm](https://user-images.githubusercontent.com/21693217/46258038-d58d9b80-c4cc-11e8-9aee-d3017e50ff38.jpg)

**Comment by Citronnn** [comment]
Ну если низ будет занят частотой ивентов, то можно туда не пихать ещё и список активности, а панельку выдвижную можно сделать справа, при этом, кнопку для её выдвижения добавить на панель сверху, рядом с About.
