### ISSUE TITLE
Нет звука, пока не пошевелишь слайдер со звуком

### ISSUE THREAD

**Issue by aaaaaa2493** [moevm/mse_voice_acting_of_activity_on_the_github#48]

**Comment by Citronnn** [comment]
Не обязательно шевелить слайдер, надо просто совершить любое взаимодействие с DOM. Причина этого - какое-то соглашение подписанное Google Chrome в апреле. Данная проблема распространяется только на localhost, в этом можно убедиться, запустив http://vladimir-turov.ru/github, тут звук сразу присутствует.

**Comment by aaaaaa2493** [comment]
Да, точно
