### ISSUE TITLE
События не выводятся на экран

### ISSUE THREAD

**Issue by aaaaaa2493** [moevm/mse_voice_acting_of_activity_on_the_github#68]

**Comment by Citronnn** [comment]
Можно подробней?
Я сейчас запустил из мастера, всё хорошо вроде бы

**Comment by aaaaaa2493** [comment]
Фильтры сохраняются но кажется, что не работают
![image](https://user-images.githubusercontent.com/20189630/49635807-ed742500-fa11-11e8-9761-da23d875a741.png)
Потому что события не отображаются
А если отключить-включить чекбокс то события начинают отображаться
